development: &development
  end_point: "https://gateway.marvel.com/"
  public_key: "b2e87ee1a6bbf8cc4ada0aaac8ae8b16"
  private_key: "d2fd3edca3b15c148da29670e879d3aa650f07ef"
production:
    <<: *development
